import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700', '800', '900'],
  variable: '--font-heading', 
});

export const metadata: Metadata = {
  title: "Foodie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` ${poppins.variable}`}>
      
      <head>
          <link 
              rel='stylesheet' 
              href='https://cdn-uicons.flaticon.com/2.4.0/uicons-bold-straight/css/uicons-bold-straight.css' 
          /> 
      </head>
      
      <body className="antialiased"> 
        {children}
      </body>
    </html>
  );
}